# -*- coding: utf-8 -*-
"""Pandas e-commerce data project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLCklK74flhGnUFYcPv44t2WTYt9hoPE
"""

import numpy as np
import pandas as pd

# ls

# from google.colab import files
# data = files.upload()

# ls

"""### **Usecase-1** Load all three csv datasets in Pandas Data frames and display first 5 records"""

cust = pd.read_csv('customers.csv',sep=",",index_col=False,names=["custno","firstname","lastname","gender","age","profession","contactNo","emailId","city","state","isActive","createdDate","UpdatedDate"])
cust.sort_values("custno",inplace=True,ignore_index=True)
# print(cust)

prod = pd.read_csv('products.csv',sep=",",index_col=False,names=["productno","productName","Description","isActive","createdDate","UpdatedDate"])
prod.sort_values("productno",inplace=True,ignore_index=True)
# print(prod)

trans = pd.read_csv('transactions.csv',sep=",",index_col=False,names=["txnno","txndate","custno","amount","productno","spendby"])
trans.sort_values("txnno",inplace=True,ignore_index=True)
# print(trans)

cust_trans = pd.merge(left=cust,right=trans,how="inner",on="custno")
# print(cust_trans)

cust_trans_prod = pd.merge(left=cust_trans, right=prod,how="inner",on="productno")
# print(cust_trans_prod)

pd.merge(left=cust_trans,right=prod,how="inner",on="productno")

b.to_excel("Sorted_Project_Data.xlsx")

# Usecase-1 Load all three csv datasets in Pandas Data frames and display first 5 records
cust_trans_prod.head()

"""### **Usecase-2** Display only those customers from CSV_s1, who purchased more than 3 products"""

cus = cust_trans_prod.groupby(["custno"])["productno"].count()
cus = cus.reset_index()
print(cus[cus["productno"]>3])

"""### **Usecase-3** Display top 5 most demanded products from CSV_s1"""

cust_trans_prod["productName"].value_counts().head(5)

"""### **Usecase-4** Display top 5 transactions amount from CSV_s1"""

cust_trans_prod["amount"].sort_values(ascending=False).head(5)

cust_trans_prod.nlargest(5,"amount",keep="all")

"""### **Usecase-5** Display distinct professions from CSV_s1"""

cust_trans_prod["profession"].unique()

"""### **Usecase-6** Display highest age in CSV_s1 customer’s dataset"""

cust.nlargest(1,"age",keep = "all")
# 28 people have age = {nlargest(64)}

"""### **Usecase-7** Display custno, gender, age, profession, contactno, productno, productName,txndate, spendby, amount from CSV_s1 for custno = 923"""

filtered_df = cust_trans_prod[["custno","gender","age","profession","contactNo","productno","productName","txndate","spendby","amount"]]
filtered_df.set_index("custno", inplace = True)
filtered_df.loc[[923]]

"""### **Usecase-8** Load all three PSV (pipe separated values) dataset in Pandas Data frames and display first 5 records"""

cust_psv = pd.read_csv("customers.txt", sep='|', index_col = False, names = ["custno","firstname","lastname","gender","age","profession","contactNo","emailId","city","state","isActive","createdDate","UpdatedDate"])
cust_psv.sort_values('custno', inplace=True, ignore_index=True)

prod_psv = pd.read_csv("products.txt", sep='|', index_col = False, names = ["productno","productName","Description","isActive","createdDate","UpdatedDate"])
prod_psv.sort_values('productno', inplace=True, ignore_index=True)

trans_psv = pd.read_csv("transactions.txt", sep='|', index_col = False, names = ["txnno","txndate","custno","amount","productno","spendby"])
trans_psv.sort_values('txnno', inplace=True, ignore_index=True)

custtrans_psv = pd.merge(cust_psv, trans_psv, on='custno', how='inner')
custtransprod_psv = pd.merge(custtrans_psv, prod_psv, on='productno', how='inner')

custtransprod_psv.head(5)

"""###  **Usecase-9** Load all three JSON datasets in Pandas Data frames and display first 5 records."""

cust_json = pd.read_json("customers.json", lines=True)
# print(df.head())

prod_json = pd.read_json("products.json", lines=True)
# print(df1.head())

trans_json = pd.read_json("transactions.json", lines=True)
# print(df2.head())

custtrans_json = pd.merge(cust_json, trans_json, on = "custno", how = "inner")
# print(Merge1)

custtransprod_json = pd.merge(custtrans_json, prod_json, on = "productno", how = "outer")
# print(Merge2.head())
custtransprod_json.head()

"""### **Usecase-10** Load all three XML datasets in Pandas Data frames and display first 5 records."""

cust_xml = pd.read_xml("customers.xml")
cust_xml.sort_values("custno", inplace = True, ignore_index = True)

prod_xml = pd.read_xml("products.xml")
prod_xml.sort_values("productno", inplace = True, ignore_index = True)

trans_xml = pd.read_xml("transactions.xml")
trans_xml.sort_values("txnno", inplace = True, ignore_index = True)

custtrans_xml = pd.merge(cust_xml, trans_xml, on = "custno", how = "inner")
custtransprod_xml = pd.merge(custtrans_xml, prod_xml, on = "productno", how = "outer")

custtransprod_xml.head(5)